import { LEAD_INTEGRATION_TYPES } from "@cadence-frontend/constants";

export const TYPES_OF_CADENCE_OPTIONS = [
	{ label: `Personal`, value: "personal" },
	{ label: `Group`, value: "team" },
	{ label: `Company`, value: "company" },
];
export const leadType = lead_integration_type => {
	switch (lead_integration_type) {
		case LEAD_INTEGRATION_TYPES.SALESFORCE_LEAD:
		case LEAD_INTEGRATION_TYPES.DYNAMICS_LEAD:
		case LEAD_INTEGRATION_TYPES.ZOHO_LEAD:
		case LEAD_INTEGRATION_TYPES.BULLHORN_LEAD:
			return "leads";
		case LEAD_INTEGRATION_TYPES.SALESFORCE_CONTACT:
		case LEAD_INTEGRATION_TYPES.DYNAMICS_CONTACT:
		case LEAD_INTEGRATION_TYPES.ZOHO_CONTACT:
		case LEAD_INTEGRATION_TYPES.BULLHORN_CONTACT:
			return "contacts";
		case LEAD_INTEGRATION_TYPES.SALESFORCE_GOOGLE_SHEET_LEAD:
		case LEAD_INTEGRATION_TYPES.SALESFORCE_CSV_LEAD:
			return "temp-leads";
		case LEAD_INTEGRATION_TYPES.BULLHORN_CANDIDATE:
			return "candidates";
		default:
			return "leads";
	}
};
export const NOT_INCLUDE_WEBSOCKET_AND_STOP_PREV_CADENCE = [
	LEAD_INTEGRATION_TYPES.EXCEL_LEAD,
	LEAD_INTEGRATION_TYPES.GOOGLE_SHEETS_LEAD,
];
export const LEAD_INTEGRATION_TYPE_MAP = {
	[LEAD_INTEGRATION_TYPES.SALESFORCE_LEAD]: "leads",
	[LEAD_INTEGRATION_TYPES.SALESFORCE_CONTACT]: "contacts",
	[LEAD_INTEGRATION_TYPES.SALESFORCE_GOOGLE_SHEET_LEAD]: "leads",
	[LEAD_INTEGRATION_TYPES.SALESFORCE_CSV_LEAD]: "leads",
	[LEAD_INTEGRATION_TYPES.PIPEDRIVE_PERSON]: "persons",
	[LEAD_INTEGRATION_TYPES.PIPEDRIVE_CSV_PERSON]: "persons",
	[LEAD_INTEGRATION_TYPES.PIPEDRIVE_GOOGLE_SHEET_PERSON]: "persons",
	[LEAD_INTEGRATION_TYPES.HUBSPOT_CONTACT]: "contacts",
	[LEAD_INTEGRATION_TYPES.HUBSPOT_CSV_CONTACT]: "contacts",
	[LEAD_INTEGRATION_TYPES.HUBSPOT_GOOGLE_SHEET_CONTACT]: "contacts",
	[LEAD_INTEGRATION_TYPES.SELLSY_CONTACT]: "contacts",
	[LEAD_INTEGRATION_TYPES.SELLSY_CSV_CONTACT]: "contacts",
	[LEAD_INTEGRATION_TYPES.SELLSY_GOOGLE_SHEET_CONTACT]: "contacts",
	[LEAD_INTEGRATION_TYPES.DYNAMICS_LEAD]: "leads",
	[LEAD_INTEGRATION_TYPES.DYNAMICS_CONTACT]: "contacts",
	[LEAD_INTEGRATION_TYPES.ZOHO_LEAD]: "leads",
	[LEAD_INTEGRATION_TYPES.ZOHO_CONTACT]: "contacts",
	[LEAD_INTEGRATION_TYPES.ZOHO_GOOGLE_SHEET_LEAD]: "leads",
	[LEAD_INTEGRATION_TYPES.ZOHO_CSV_LEAD]: "leads",
	[LEAD_INTEGRATION_TYPES.BULLHORN_LEAD]: "leads",
	[LEAD_INTEGRATION_TYPES.BULLHORN_CONTACT]: "contacts",
	[LEAD_INTEGRATION_TYPES.BULLHORN_CANDIDATE]: "candidates",
	[LEAD_INTEGRATION_TYPES.BULLHORN_CSV_LEAD]: "leads",
	[LEAD_INTEGRATION_TYPES.BULLHORN_GOOGLE_SHEET_LEAD]: "leads",
	[LEAD_INTEGRATION_TYPES.EXCEL_LEAD]: "leads",
	[LEAD_INTEGRATION_TYPES.GOOGLE_SHEETS_LEAD]: "leads",
};
