import { Cadence as CADENCE_TRANSLATION } from "@cadence-frontend/languages";

export const TYPE_MAP = {
	LEAD: CADENCE_TRANSLATION.LEAD,
	LEAD_NOT_ASSOCIATED: CADENCE_TRANSLATION.LEAD_NOT_ASSOCIATED,
	CADENCE: CADENCE_TRANSLATION.CADENCE_DOES_NOT_EXIST,
	CADENCE_NOT_ASSOCIATED: CADENCE_TRANSLATION.CADENCE_NOT_ASSOCIATED,
};
