import { render, screen } from "@cadence-frontend/test-utils";
import "@testing-library/jest-dom";
import TaskInfo from "./TaskInfo";
import { rest } from "msw";
import { setupServer } from "msw/node";
import { ENV } from "@cadence-frontend/environments";

const activeTaskInfo = {
	task_id: 30942,
	user_id: "49ed6822-df47-4df9-ae2a-737e3a861f7a",
	name: "2",
	completed: false,
	complete_time: null,
	is_skipped: false,
	start_time: 1675751628861,
	shown_time: 1675751629444,
	late_time: 1675838029444,
	created_at: "2023-02-07T06:33:48.000Z",
	Lead: {
		first_name: "Giorno",
		last_name: "Giovanna",
		lead_id: 33673,
		job_position: "Soldato",
		duplicate: null,
		Account: { account_id: 30010, size: "500-1000", name: "Passione" },
		Lead_phone_numbers: [
			{ time: "1:00:40 AM", is_primary: false, timezone: "America/Adak" },
			{ time: "", is_primary: false, timezone: null },
			{ time: "1:00:40 AM", is_primary: true, timezone: "America/Adak" },
		],
	},
	Cadence: {
		name: "Outbound prospecting Cadence",
		cadence_id: 30170,
		Nodes: [
			{ node_id: 31187 },
			{ node_id: 31188 },
			{ node_id: 31189 },
			{ node_id: 31190 },
			{ node_id: 31192 },
			{ node_id: 31193 },
			{ node_id: 31194 },
			{ node_id: 31197 },
			{ node_id: 31183 },
			{ node_id: 31186 },
			{ node_id: 31181 },
			{ node_id: 31185 },
		],
	},
	Node: {
		node_id: 31185,
		type: "message",
		step_number: 3,
		data: { message: "Hello", template_id: 2, template_type: "sms" },
		next_node_id: 31186,
		is_urgent: false,
		isLate: 0,
	},
};

const leadData = {
	lead: {
		data: {
			lead_id: 33673,
			first_name: "Giorno",
			last_name: "Giovanna",
			full_name: "Giorno Giovanna",
			job_position: "Soldato",
			user_id: "49ed6822-df47-4df9-ae2a-737e3a861f7a",
			salesforce_lead_id: null,
			salesforce_contact_id: "0032w00000y5IquAAE",
			account_id: 30010,
			duplicate: null,
			linkedin_url: "https://linkedin.com/in/shivamvijay1465",
			status: "new_lead",
			type: "header_form",
			created_at: "2023-02-05T13:54:55.000Z",
			integration_id: "0032w00000y5IquAAE",
			integration_type: "salesforce_contact",
			User: {
				user_id: "49ed6822-df47-4df9-ae2a-737e3a861f7a",
				first_name: "Yuvraj",
				last_name: "Singh",
				sd_id: "40d9cbc2-0203-41e0-b086-414b5509d7cc",
				primary_email: "exploration.exterprise2022@gmail.com",
				primary_phone_number: "+33755523632",
				calendly_url: "",
				User_Token: {
					salesforce_instance_url:
						"https://explorationenterprise-dev-ed.develop.my.salesforce.com",
				},
				Salesforce_Token: {
					access_token:
						"00D2w00000Jbp2Z!AR0AQFuoCo4CTAIpESgNvoyCo1WkBVR7cmfdCGGGha0iSvJ5tgo.M2NN1KBaPowFN_zeVLiLvqzevT_nouHNLzWyrvONoB1w",
					refresh_token:
						"5Aep861ZBQbtA4s3JXbFr00XwhReq8biQDi7PyNzFWnOC1UJmK2kaD9gMANBI8SvrHeX09oA3gyeYDOjjRJ9GxD",
					instance_url: "https://explorationenterprise-dev-ed.develop.my.salesforce.com",
					salesforce_token_id: 1,
					is_logged_out: false,
					user_id: "49ed6822-df47-4df9-ae2a-737e3a861f7a",
					created_at: "2022-12-22T06:46:42.000Z",
					updated_at: "2023-02-07T06:10:34.000Z",
				},
				Company: {
					name: "Exploration Enterprise",
					company_id: "f9411bdf-1d98-46bb-900e-e2ee78289f76",
					Company_Setting: {
						company_settings_id: 2,
						Salesforce_Field_Map: {
							sfm_id: 1,
							account_map: {
								country: "BillingCountry",
								disqualification_reason: {
									name: "DisqualificationReason",
									picklist_values: [{ label: "not responding", value: "not responding" }],
								},
								integration_status: {
									converted: { label: "Converted", value: "Converted" },
									disqualified: {
										label: "Not Interested",
										value: "Not Interested",
									},
									name: "Onboarding__c",
									picklist_values: [
										{ label: "New", value: "New" },
										{ label: "Ongoing", value: "Ongoing" },
										{ label: "Interested", value: "Interested" },
										{ label: "Not Interested", value: "Not Interested" },
										{ label: "Converted", value: "Converted" },
									],
								},
								name: "Name",
								phone_number: "Phone",
								size: "No_of_Employees__c",
								url: "Website",
								variables: [],
								zip_code: "BillingPostalCode",
							},
							lead_map: {
								company: "Company",
								country: "Country",
								disqualification_reason: {
									name: "DisqualificationReason",
									picklist_values: [{ label: "test", value: "test" }],
								},
								emails: ["Email"],
								first_name: "FirstName",
								integration_status: {
									converted: {
										label: "Closed - Converted",
										value: "Closed - Converted",
									},
									disqualified: {
										label: "Closed - Not Converted",
										value: "Closed - Not Converted",
									},
									name: "Status",
									picklist_values: [
										{
											label: "Open - Not Contacted",
											value: "Open - Not Contacted",
										},
										{
											label: "Working - Contacted",
											value: "Working - Contacted",
										},
										{ label: "Closed - Converted", value: "Closed - Converted" },
										{
											label: "Closed - Not Converted",
											value: "Closed - Not Converted",
										},
									],
								},
								job_position: "Title",
								last_name: "LastName",
								linkedin_url: "Linkedin__c",
								phone_numbers: ["Phone", "MobilePhone"],
								size: "SizePicklist__c",
								url: "Website",
								variables: [
									{
										target_value: { label: "City", value: "City" },
										variable_field_name: "Variable 1",
									},
									{
										target_value: {
											label: "Company D-U-N-S Number",
											value: "CompanyDunsNumber",
										},
										variable_field_name: "Variable 2",
									},
								],
								zip_code: "PostalCode",
							},
							contact_map: {
								emails: ["Email"],
								first_name: "FirstName",
								job_position: "Title",
								last_name: "LastName",
								linkedin_url: "LinkedIn__c",
								phone_numbers: ["Phone", "MobilePhone", "OtherPhone"],
								variables: [
									{
										target_value: { label: "Account ID", value: "AccountId" },
										variable_field_name: "Variable 1",
									},
									{
										target_value: { label: "Birthdate", value: "Birthdate" },
										variable_field_name: "Variable 2",
									},
									{
										target_value: { label: "Full Name", value: "Name" },
										variable_field_name: "Variable 3",
									},
									{
										target_value: { label: "Mailing City", value: "MailingCity" },
										variable_field_name: "Variable 4",
									},
								],
							},
							lead_custom_object: [
								{
									button_text: "Qualification",
									form: [
										{
											editable: true,
											input_type: "string",
											position: { column: 0, row: 0 },
											salesforce_field: "FirstName",
											salesforce_label: "First Name",
											sobject: "lead",
											type: "input_box",
										},
										{
											editable: true,
											input_type: "string",
											position: { column: 1, row: 0 },
											salesforce_field: "LastName",
											salesforce_label: "Last Name",
											sobject: "lead",
											type: "input_box",
										},
										{
											editable: true,
											input_type: "string",
											position: { column: 2, row: 0 },
											salesforce_field: "Company",
											salesforce_label: "Company",
											sobject: "lead",
											type: "input_box",
										},
										{
											editable: true,
											input_type: "currency",
											position: { column: 2, row: 1 },
											salesforce_field: "AnnualRevenue",
											salesforce_label: "Annual Revenue",
											sobject: "lead",
											type: "input_box",
										},
										{
											editable: true,
											input_type: "string",
											position: { column: 1, row: 1 },
											salesforce_field: "City",
											salesforce_label: "City",
											sobject: "lead",
											type: "input_box",
										},
										{
											editable: true,
											position: { column: 0, row: 1 },
											possible_values: [
												{
													active: true,
													defaultValue: false,
													label: "In Sync",
													validFor: null,
													value: "Matched",
												},
												{
													active: true,
													defaultValue: false,
													label: "Different",
													validFor: null,
													value: "Different",
												},
												{
													active: true,
													defaultValue: false,
													label: "Reviewed",
													validFor: null,
													value: "Acknowledged",
												},
												{
													active: true,
													defaultValue: false,
													label: "Not Found",
													validFor: null,
													value: "NotFound",
												},
												{
													active: true,
													defaultValue: false,
													label: "Inactive",
													validFor: null,
													value: "Inactive",
												},
												{
													active: true,
													defaultValue: false,
													label: "Not Compared",
													validFor: null,
													value: "Pending",
												},
												{
													active: true,
													defaultValue: false,
													label: "Select Match",
													validFor: null,
													value: "SelectMatch",
												},
												{
													active: true,
													defaultValue: false,
													label: "Skipped",
													validFor: null,
													value: "Skipped",
												},
											],
											salesforce_field: "CleanStatus",
											salesforce_label: "Clean Status",
											sobject: "lead",
											type: "dropdown",
										},
										{
											editable: false,
											position: { column: 2, row: 2 },
											reference_field_name: {
												label: "Account Name",
												name: "Name",
												sObject: "Account",
											},
											reference_to: "Account",
											salesforce_field: "ConvertedAccountId",
											salesforce_label: "Converted Account ID",
											sobject: "lead",
											type: "dropdown",
										},
										{
											editable: false,
											position: { column: 1, row: 2 },
											reference_field_name: {
												label: "Full Name",
												name: "Name",
												sObject: "Contact",
											},
											reference_to: "Contact",
											salesforce_field: "ConvertedContactId",
											salesforce_label: "Converted Contact ID",
											sobject: "lead",
											type: "dropdown",
										},
										{
											editable: false,
											input_type: "date",
											position: { column: 0, row: 2 },
											salesforce_field: "ConvertedDate",
											salesforce_label: "Converted Date",
											sobject: "lead",
											type: "input_box",
										},
										{
											editable: true,
											input_type: "string",
											position: { column: 2, row: 3 },
											salesforce_field: "CurrentGenerators__c",
											salesforce_label: "Current Generator(s)",
											sobject: "lead",
											type: "input_box",
										},
										{
											editable: true,
											position: { column: 1, row: 3 },
											reference_field_name: {
												label: "Primary Business Name",
												name: "Name",
												sObject: "DandBCompany",
											},
											reference_to: "DandBCompany",
											salesforce_field: "DandbCompanyId",
											salesforce_label: "D&B Company ID",
											sobject: "lead",
											type: "dropdown",
										},
										{
											editable: true,
											input_type: "string",
											position: { column: 0, row: 3 },
											salesforce_field: "Jigsaw",
											salesforce_label: "Data.com Key",
											sobject: "lead",
											type: "input_box",
										},
										{
											editable: false,
											position: { column: 2, row: 4 },
											salesforce_field: "IsDeleted",
											salesforce_label: "Deleted",
											sobject: "lead",
											type: "radio_button",
										},
										{
											editable: true,
											input_type: "textarea",
											position: { column: 1, row: 4 },
											salesforce_field: "Description",
											salesforce_label: "Description",
											sobject: "lead",
											type: "input_box",
										},
										{
											editable: true,
											input_type: "email",
											position: { column: 0, row: 4 },
											salesforce_field: "Email",
											salesforce_label: "Email",
											sobject: "lead",
											type: "input_box",
										},
										{
											editable: true,
											input_type: "string",
											position: { column: 2, row: 5 },
											salesforce_field: "Country",
											salesforce_label: "Country",
											sobject: "lead",
											type: "input_box",
										},
										{
											editable: false,
											position: { column: 1, row: 5 },
											reference_field_name: {
												label: "Full Name",
												name: "Name",
												sObject: "User",
											},
											reference_to: "User",
											salesforce_field: "CreatedById",
											salesforce_label: "Created By ID",
											sobject: "lead",
											type: "dropdown",
										},
										{
											editable: false,
											input_type: "datetime",
											position: { column: 0, row: 5 },
											salesforce_field: "CreatedDate",
											salesforce_label: "Created Date",
											sobject: "lead",
											type: "input_box",
										},
										{
											editable: true,
											input_type: "datetime",
											position: { column: 2, row: 6 },
											salesforce_field: "EmailBouncedDate",
											salesforce_label: "Email Bounced Date",
											sobject: "lead",
											type: "input_box",
										},
										{
											editable: true,
											input_type: "int",
											position: { column: 0, row: 6 },
											salesforce_field: "NumberOfEmployees",
											salesforce_label: "Employees",
											sobject: "lead",
											type: "input_box",
										},
										{
											editable: false,
											input_type: "string",
											position: { column: 1, row: 7 },
											salesforce_field: "Name",
											salesforce_label: "Full Name",
											sobject: "lead",
											type: "input_box",
										},
										{
											editable: true,
											position: { column: 0, row: 7 },
											possible_values: [
												{
													active: true,
													defaultValue: false,
													label: "Address",
													validFor: null,
													value: "Address",
												},
												{
													active: true,
													defaultValue: false,
													label: "NearAddress",
													validFor: null,
													value: "NearAddress",
												},
												{
													active: true,
													defaultValue: false,
													label: "Block",
													validFor: null,
													value: "Block",
												},
												{
													active: true,
													defaultValue: false,
													label: "Street",
													validFor: null,
													value: "Street",
												},
												{
													active: true,
													defaultValue: false,
													label: "ExtendedZip",
													validFor: null,
													value: "ExtendedZip",
												},
												{
													active: true,
													defaultValue: false,
													label: "Zip",
													validFor: null,
													value: "Zip",
												},
												{
													active: true,
													defaultValue: false,
													label: "Neighborhood",
													validFor: null,
													value: "Neighborhood",
												},
												{
													active: true,
													defaultValue: false,
													label: "City",
													validFor: null,
													value: "City",
												},
												{
													active: true,
													defaultValue: false,
													label: "County",
													validFor: null,
													value: "County",
												},
												{
													active: true,
													defaultValue: false,
													label: "State",
													validFor: null,
													value: "State",
												},
												{
													active: true,
													defaultValue: false,
													label: "Unknown",
													validFor: null,
													value: "Unknown",
												},
											],
											salesforce_field: "GeocodeAccuracy",
											salesforce_label: "Geocode Accuracy",
											sobject: "lead",
											type: "dropdown",
										},
										{
											editable: true,
											position: { column: 2, row: 8 },
											salesforce_field: "RingoverCadence__Has_Active_Cadence__c",
											salesforce_label: "Has Active Cadence",
											sobject: "lead",
											type: "radio_button",
										},
										{
											editable: true,
											position: { column: 1, row: 8 },
											possible_values: [
												{
													active: true,
													defaultValue: false,
													label: "Agriculture",
													validFor: null,
													value: "Agriculture",
												},
												{
													active: true,
													defaultValue: false,
													label: "Apparel",
													validFor: null,
													value: "Apparel",
												},
												{
													active: true,
													defaultValue: false,
													label: "Banking",
													validFor: null,
													value: "Banking",
												},
												{
													active: true,
													defaultValue: false,
													label: "Biotechnology",
													validFor: null,
													value: "Biotechnology",
												},
												{
													active: true,
													defaultValue: false,
													label: "Chemicals",
													validFor: null,
													value: "Chemicals",
												},
												{
													active: true,
													defaultValue: false,
													label: "Communications",
													validFor: null,
													value: "Communications",
												},
												{
													active: true,
													defaultValue: false,
													label: "Construction",
													validFor: null,
													value: "Construction",
												},
												{
													active: true,
													defaultValue: false,
													label: "Consulting",
													validFor: null,
													value: "Consulting",
												},
												{
													active: true,
													defaultValue: false,
													label: "Education",
													validFor: null,
													value: "Education",
												},
												{
													active: true,
													defaultValue: false,
													label: "Electronics",
													validFor: null,
													value: "Electronics",
												},
												{
													active: true,
													defaultValue: false,
													label: "Energy",
													validFor: null,
													value: "Energy",
												},
												{
													active: true,
													defaultValue: false,
													label: "Engineering",
													validFor: null,
													value: "Engineering",
												},
												{
													active: true,
													defaultValue: false,
													label: "Entertainment",
													validFor: null,
													value: "Entertainment",
												},
												{
													active: true,
													defaultValue: false,
													label: "Environmental",
													validFor: null,
													value: "Environmental",
												},
												{
													active: true,
													defaultValue: false,
													label: "Finance",
													validFor: null,
													value: "Finance",
												},
												{
													active: true,
													defaultValue: false,
													label: "Food & Beverage",
													validFor: null,
													value: "Food & Beverage",
												},
												{
													active: true,
													defaultValue: false,
													label: "Government",
													validFor: null,
													value: "Government",
												},
												{
													active: true,
													defaultValue: false,
													label: "Healthcare",
													validFor: null,
													value: "Healthcare",
												},
												{
													active: true,
													defaultValue: false,
													label: "Hospitality",
													validFor: null,
													value: "Hospitality",
												},
												{
													active: true,
													defaultValue: false,
													label: "Insurance",
													validFor: null,
													value: "Insurance",
												},
												{
													active: true,
													defaultValue: false,
													label: "Machinery",
													validFor: null,
													value: "Machinery",
												},
												{
													active: true,
													defaultValue: false,
													label: "Manufacturing",
													validFor: null,
													value: "Manufacturing",
												},
												{
													active: true,
													defaultValue: false,
													label: "Media",
													validFor: null,
													value: "Media",
												},
												{
													active: true,
													defaultValue: false,
													label: "Not For Profit",
													validFor: null,
													value: "Not For Profit",
												},
												{
													active: true,
													defaultValue: false,
													label: "Recreation",
													validFor: null,
													value: "Recreation",
												},
												{
													active: true,
													defaultValue: false,
													label: "Retail",
													validFor: null,
													value: "Retail",
												},
												{
													active: true,
													defaultValue: false,
													label: "Shipping",
													validFor: null,
													value: "Shipping",
												},
												{
													active: true,
													defaultValue: false,
													label: "Technology",
													validFor: null,
													value: "Technology",
												},
												{
													active: true,
													defaultValue: false,
													label: "Telecommunications",
													validFor: null,
													value: "Telecommunications",
												},
												{
													active: true,
													defaultValue: false,
													label: "Transportation",
													validFor: null,
													value: "Transportation",
												},
												{
													active: true,
													defaultValue: false,
													label: "Utilities",
													validFor: null,
													value: "Utilities",
												},
												{
													active: true,
													defaultValue: false,
													label: "Other",
													validFor: null,
													value: "Other",
												},
											],
											salesforce_field: "Industry",
											salesforce_label: "Industry",
											sobject: "lead",
											type: "dropdown",
										},
										{
											editable: true,
											position: { column: 0, row: 8 },
											reference_field_name: {
												label: "Name",
												name: "Name",
												sObject: "Individual",
											},
											reference_to: "Individual",
											salesforce_field: "IndividualId",
											salesforce_label: "Individual ID",
											sobject: "lead",
											type: "dropdown",
										},
										{
											editable: false,
											input_type: "string",
											position: { column: 2, row: 9 },
											salesforce_field: "JigsawContactId",
											salesforce_label: "Jigsaw Contact ID",
											sobject: "lead",
											type: "input_box",
										},
										{
											editable: false,
											input_type: "date",
											position: { column: 1, row: 9 },
											salesforce_field: "LastActivityDate",
											salesforce_label: "Last Activity",
											sobject: "lead",
											type: "input_box",
										},
										{
											editable: false,
											position: { column: 0, row: 9 },
											reference_field_name: {
												label: "Full Name",
												name: "Name",
												sObject: "User",
											},
											reference_to: "User",
											salesforce_field: "LastModifiedById",
											salesforce_label: "Last Modified By ID",
											sobject: "lead",
											type: "dropdown",
										},
										{
											editable: false,
											input_type: "datetime",
											position: { column: 2, row: 10 },
											salesforce_field: "LastModifiedDate",
											salesforce_label: "Last Modified Date",
											sobject: "lead",
											type: "input_box",
										},
										{
											editable: false,
											input_type: "datetime",
											position: { column: 1, row: 10 },
											salesforce_field: "LastReferencedDate",
											salesforce_label: "Last Referenced Date",
											sobject: "lead",
											type: "input_box",
										},
										{
											editable: false,
											input_type: "datetime",
											position: { column: 0, row: 10 },
											salesforce_field: "LastViewedDate",
											salesforce_label: "Last Viewed Date",
											sobject: "lead",
											type: "input_box",
										},
										{
											editable: true,
											input_type: "double",
											position: { column: 2, row: 11 },
											salesforce_field: "Latitude",
											salesforce_label: "Latitude",
											sobject: "lead",
											type: "input_box",
										},
										{
											editable: false,
											input_type: "id",
											position: { column: 1, row: 11 },
											salesforce_field: "Id",
											salesforce_label: "Lead ID",
											sobject: "lead",
											type: "input_box",
										},
										{
											editable: true,
											position: { column: 0, row: 11 },
											possible_values: [
												{
													active: true,
													defaultValue: false,
													label: "Web",
													validFor: null,
													value: "Web",
												},
												{
													active: true,
													defaultValue: false,
													label: "Phone Inquiry",
													validFor: null,
													value: "Phone Inquiry",
												},
												{
													active: true,
													defaultValue: false,
													label: "Partner Referral",
													validFor: null,
													value: "Partner Referral",
												},
												{
													active: true,
													defaultValue: false,
													label: "Purchased List",
													validFor: null,
													value: "Purchased List",
												},
												{
													active: true,
													defaultValue: false,
													label: "Other",
													validFor: null,
													value: "Other",
												},
											],
											salesforce_field: "LeadSource",
											salesforce_label: "Lead Source",
											sobject: "lead",
											type: "dropdown",
										},
										{
											editable: false,
											input_type: "url",
											position: { column: 2, row: 7 },
											salesforce_field: "PhotoUrl",
											salesforce_label: "Photo URL",
											sobject: "lead",
											type: "input_box",
										},
										{
											editable: true,
											input_type: "phone",
											position: { column: 1, row: 6 },
											salesforce_field: "Phone",
											salesforce_label: "Phone",
											sobject: "lead",
											type: "input_box",
										},
									],
								},
							],
							contact_custom_object: [
								{
									button_text: "Qualification",
									form: [
										{
											editable: true,
											input_type: "string",
											position: { column: 0, row: 0 },
											salesforce_field: "Name",
											salesforce_label: "Account Name",
											sobject: "account",
											type: "input_box",
										},
										{
											editable: true,
											input_type: "string",
											position: { column: 1, row: 0 },
											salesforce_field: "FirstName",
											salesforce_label: "First Name",
											sobject: "contact",
											type: "input_box",
										},
										{
											editable: true,
											input_type: "string",
											position: { column: 2, row: 0 },
											salesforce_field: "LastName",
											salesforce_label: "Last Name",
											sobject: "contact",
											type: "input_box",
										},
										{
											editable: false,
											input_type: "id",
											position: { column: 2, row: 1 },
											salesforce_field: "Id",
											salesforce_label: "Account ID",
											sobject: "account",
											type: "input_box",
										},
										{
											editable: true,
											input_type: "string",
											position: { column: 1, row: 1 },
											salesforce_field: "BillingCity",
											salesforce_label: "Billing City",
											sobject: "account",
											type: "input_box",
										},
									],
								},
							],
							company_settings_id: 2,
							created_at: "2022-12-22T06:46:42.000Z",
							updated_at: "2023-02-06T15:44:37.000Z",
						},
						Webhooks: [],
					},
				},
			},
			Account: {
				account_id: 30010,
				salesforce_account_id: null,
				user_id: "49ed6822-df47-4df9-ae2a-737e3a861f7a",
				name: "Passione",
				size: "500-1000",
				zipcode: null,
				country: "US",
				phone_number: "+1 (844) 411-1221",
				integration_id: "0012w00001FljoHAAR",
				integration_type: "salesforce_account",
			},
			Lead_phone_numbers: [
				{
					formatted_phone_number: "",
					time: "",
					lpn_id: 34619,
					phone_number: "",
					type: "MobilePhone",
					timezone: null,
					is_primary: false,
				},
				{
					formatted_phone_number: "15458954283",
					time: "12:24:28 AM",
					lpn_id: 34620,
					phone_number: "+1 (545) 895-4283",
					type: "OtherPhone",
					timezone: "America/Adak",
					is_primary: false,
				},
				{
					formatted_phone_number: "15667113902",
					time: "12:24:28 AM",
					lpn_id: 34618,
					phone_number: "+1 (566) 711-3902",
					type: "Phone",
					timezone: "America/Adak",
					is_primary: true,
				},
			],
			Lead_emails: [
				{
					lem_id: 34223,
					email_id: "regecyqyq@mailinator.com",
					is_primary: true,
					type: "Email",
				},
			],
			LeadToCadences: [
				{
					status: "in_progress",
					Cadences: [
						{
							cadence_id: 30170,
							name: "Outbound prospecting Cadence",
							salesforce_cadence_id: "a012w000015XGnNAAW",
							status: "in_progress",
							unix_resume_at: null,
							Nodes: [
								{ node_id: 31197 },
								{ node_id: 31181 },
								{ node_id: 31183 },
								{ node_id: 31185 },
								{ node_id: 31186 },
								{ node_id: 31187 },
								{ node_id: 31188 },
								{ node_id: 31189 },
								{ node_id: 31190 },
								{ node_id: 31192 },
								{ node_id: 31193 },
								{ node_id: 31194 },
							],
						},
					],
					Tasks: [{ task_id: 30942, Node: { type: "message", step_number: 3 } }],
				},
			],
		},
		msg: "Lead fetched successfully.",
		success: true,
	},
	activities: {
		data: [
			{
				activity_id: 116778,
				name: "Outbound prospecting Cadence Launched",
				type: "launch_cadence",
				status: "Cadence Launched by Yuvraj Singh at 1675605297",
				comment: null,
				recording: null,
				voicemail: null,
				to_number: null,
				from_number: null,
				incoming: null,
				read: false,
				ringover_call_id: null,
				salesforce_task_id: null,
				message_id: null,
				sent_message_id: null,
				gmail_message_id: null,
				note_id: null,
				cadence_id: 30170,
				node_id: null,
				task_id: null,
				created_at: "2023-02-05T13:54:56.000Z",
				updated_at: "2023-02-05T13:54:56.000Z",
				lead_id: 33673,
				Cadence: { name: "Outbound prospecting Cadence" },
				Email: null,
			},
			{
				activity_id: 117301,
				name: "Outbound prospecting Cadence has been paused",
				type: "pause_cadence",
				status: "Cadence Paused",
				comment: null,
				recording: null,
				voicemail: null,
				to_number: null,
				from_number: null,
				incoming: null,
				read: false,
				ringover_call_id: null,
				salesforce_task_id: null,
				message_id: null,
				sent_message_id: null,
				gmail_message_id: null,
				note_id: null,
				cadence_id: 30170,
				node_id: null,
				task_id: null,
				created_at: "2023-02-06T13:29:31.000Z",
				updated_at: "2023-02-06T13:29:31.000Z",
				lead_id: 33673,
				Cadence: { name: "Outbound prospecting Cadence" },
				Email: null,
			},
			{
				activity_id: 117324,
				name: "Outbound prospecting Cadence resumed",
				type: "resume_cadence",
				status: "Cadence Resumed",
				comment: null,
				recording: null,
				voicemail: null,
				to_number: null,
				from_number: null,
				incoming: null,
				read: false,
				ringover_call_id: null,
				salesforce_task_id: null,
				message_id: null,
				sent_message_id: null,
				gmail_message_id: null,
				note_id: null,
				cadence_id: null,
				node_id: 31181,
				task_id: null,
				created_at: "2023-02-06T13:29:43.000Z",
				updated_at: "2023-02-06T13:29:43.000Z",
				lead_id: 33673,
				Cadence: null,
				Email: null,
			},
			{
				activity_id: 117357,
				name: "User has skipped task",
				type: "task_skipped",
				status: "Semi Automated Mail has been manually skipped",
				comment: null,
				recording: null,
				voicemail: null,
				to_number: null,
				from_number: null,
				incoming: null,
				read: false,
				ringover_call_id: null,
				salesforce_task_id: null,
				message_id: null,
				sent_message_id: null,
				gmail_message_id: null,
				note_id: null,
				cadence_id: 30170,
				node_id: 31181,
				task_id: null,
				created_at: "2023-02-07T06:33:47.000Z",
				updated_at: "2023-02-07T06:33:47.000Z",
				lead_id: 33673,
				Cadence: { name: "Outbound prospecting Cadence" },
				Email: null,
			},
			{
				activity_id: 117374,
				name: "Outbound prospecting Cadence has been paused",
				type: "pause_cadence",
				status: "Cadence Paused",
				comment: null,
				recording: null,
				voicemail: null,
				to_number: null,
				from_number: null,
				incoming: null,
				read: false,
				ringover_call_id: null,
				salesforce_task_id: null,
				message_id: null,
				sent_message_id: null,
				gmail_message_id: null,
				note_id: null,
				cadence_id: 30170,
				node_id: null,
				task_id: null,
				created_at: "2023-02-07T06:34:15.000Z",
				updated_at: "2023-02-07T06:34:15.000Z",
				lead_id: 33673,
				Cadence: { name: "Outbound prospecting Cadence" },
				Email: null,
			},
			{
				activity_id: 117392,
				name: "Outbound prospecting Cadence resumed",
				type: "resume_cadence",
				status: "Cadence Resumed",
				comment: null,
				recording: null,
				voicemail: null,
				to_number: null,
				from_number: null,
				incoming: null,
				read: false,
				ringover_call_id: null,
				salesforce_task_id: null,
				message_id: null,
				sent_message_id: null,
				gmail_message_id: null,
				note_id: null,
				cadence_id: null,
				node_id: 31185,
				task_id: null,
				created_at: "2023-02-07T06:34:31.000Z",
				updated_at: "2023-02-07T06:34:31.000Z",
				lead_id: 33673,
				Cadence: null,
				Email: null,
			},
		],
		msg: "Activities fetched successfully.",
		success: true,
	},
	nextNode: { type: "call", wait_time: 0 },
};

const server = setupServer(
	rest.get(`${ENV.BACKEND}/v2/sales/lead/:leadId`, (req, res, ctx) =>
		req.params?.leadId === "33673"
			? res(ctx.status(200), ctx.json(leadData))
			: res(ctx.status(404))
	)
);

beforeAll(() => server.listen());
afterEach(() => server.resetHandlers());
afterAll(() => server.close());

test("renders", async () => {
	render(<TaskInfo activeTaskInfo={activeTaskInfo} userId={null} />);

	await screen.findByText("Outbound prospecting Cadence");
	await screen.findByText(/task.*30942/i);
	await screen.findByText(/17% done/i);
	await screen.findByText(/step 3\/12/i);
	await screen.findByRole("button", {
		name: /skip task/i,
	});
	await screen.findByRole("button", {
		name: /pause cadence/i,
	});
	await screen.findByRole("button", {
		name: /stop cadence/i,
	});
	await screen.findByRole("button", {
		name: /semi automatic sms/i,
	});
	await screen.findByRole("button", {
		name: /add note/i,
	});
	await screen.findByRole("button", {
		name: /custom/i,
	});
});
