import { LEAD_INTEGRATION_TYPES } from "@cadence-frontend/constants";

export const ENTITY_TYPES = {
	LEAD: LEAD_INTEGRATION_TYPES.SALESFORCE_LEAD,
	CONTACT: LEAD_INTEGRATION_TYPES.SALESFORCE_CONTACT,
};
