import { SETTING_PRIORITY } from "@cadence-frontend/constants";
import {
	Settings as SETTINGS_TRANSLATION,
	Tasks as TASKS_TRANSLATION,
} from "@cadence-frontend/languages";

export const TIME_OPTIONS = {
	MINUTES: "Minutes",
	SECONDS: "Seconds",
};

export const LEAD_SCORE_PANELS = {
	EMAIL_CLICKED: SETTINGS_TRANSLATION.EMAIL_CLICKED,
	EMAIL_OPENED: SETTINGS_TRANSLATION.EMAIL_OPENED,
	EMAIL_REPLIED: SETTINGS_TRANSLATION.EMAIL_REPLIED,
	INCOMING_CALL: SETTINGS_TRANSLATION.INCOMING_CALL_RECEIVED,
	SMS_CLICKED: SETTINGS_TRANSLATION.SMS_LINK_CLICKED,
	UNSUBSCRIBE: SETTINGS_TRANSLATION.LEAD_UNSUBSCRIBED_TO_CADENCE,
	BOUNCED_MAIL: SETTINGS_TRANSLATION.BOUNCED_MAIL,
	OUTGOING_CALL: SETTINGS_TRANSLATION.OUTGOING_CALL,
	DEMO_BOOKED: TASKS_TRANSLATION.DEMO_BOOKED,
	STATUS_UPDATE: SETTINGS_TRANSLATION.STATUS_UPDATE,
	RESET_SCORE: SETTINGS_TRANSLATION.RESET_SCORE,
	SCORE_THRESHOLD: SETTINGS_TRANSLATION.HOT_LEAD_POINTS,
};

export const LEAD_SCORE_KEYS = {
	EMAIL_CLICKED: "email_clicked",
	EMAIL_OPENED: "email_opened",
	EMAIL_REPLIED: "email_replied",
	INCOMING_CALL: "incoming_call_received",
	SMS_CLICKED: "sms_clicked",
	UNSUBSCRIBE: "unsubscribe",
	BOUNCED_MAIL: "bounced_mail",
	OUTGOING_CALL_DURATION: "outgoing_call_duration",
	OUTGOING_CALL: "outgoing_call",
	DEMO_BOOKED: "demo_booked",
	STATUS_UPDATE: "status_update",
	RESET_SCORE: "reset_period",
	SCORE_THRESHOLD: "score_threshold",
};

export const ALLOWED_INTEGRATIONS_FOR_STATUS_POINTS = ["salesforce", "hubspot"];
