export default {
	TRANSPARENT: "TRANSPARENT",
	PRIMARY: "PRIMARY",
	SECONDARY: "SECONDARY",
	RED: "RED",
	PINK: "PINK",
	GREY: "GREY",
	WHITE: "WHITE",
	ACTIVE: "ACTIVE",
	GREEN: "GREEN",
	ICON: "ICON",
};
