import INTEGRATION_TYPE from "./integrationType";
import LEAD_INTEGRATION_TYPES from "./leadIntegrationTypes";

export const CRM_CUSTOM_VARIABLES = {
	LEAD: "custom_lead_variables",
	CONTACT: "custom_contact_variables",
	ACCOUNT: "custom_account_variables",
	CANDIDATE: "custom_candidate_variables",
};

export const IS_CUSTOM_VARS_AVAILABLE = [
	INTEGRATION_TYPE.SALESFORCE,
	INTEGRATION_TYPE.PIPEDRIVE,
	INTEGRATION_TYPE.HUBSPOT,
	INTEGRATION_TYPE.ZOHO,
	INTEGRATION_TYPE.SELLSY,
	INTEGRATION_TYPE.BULLHORN,
];

export const IS_CUSTOM_VARS_AVL_FOR_LEAD_INTEGRATION = [
	LEAD_INTEGRATION_TYPES.SALESFORCE_LEAD,
	LEAD_INTEGRATION_TYPES.SALESFORCE_CONTACT,
	LEAD_INTEGRATION_TYPES.PIPEDRIVE_PERSON,
	LEAD_INTEGRATION_TYPES.HUBSPOT_CONTACT,
	LEAD_INTEGRATION_TYPES.ZOHO_LEAD,
	LEAD_INTEGRATION_TYPES.ZOHO_CONTACT,
	LEAD_INTEGRATION_TYPES.SELLSY_CONTACT,
	LEAD_INTEGRATION_TYPES.BULLHORN_LEAD,
	LEAD_INTEGRATION_TYPES.BULLHORN_CONTACT,
	LEAD_INTEGRATION_TYPES.BULLHORN_CANDIDATE,
];
