export default {
	SALESFORCE_LEAD: "salesforce_lead",
	SALESFORCE_CONTACT: "salesforce_contact",
	SALESFORCE_GOOGLE_SHEET_LEAD: "salesforce_google_sheet_lead",
	SALESFORCE_CSV_LEAD: "salesforce_csv_lead",
	PIPEDRIVE_PERSON: "pipedrive_person",
	PIPEDRIVE_GOOGLE_SHEET_PERSON: "pipedrive_google_sheet_person",
	PIPEDRIVE_CSV_PERSON: "pipedrive_csv_person",
	HUBSPOT_CONTACT: "hubspot_contact",
	HUBSPOT_GOOGLE_SHEET_CONTACT: "hubspot_google_sheet_contact",
	HUBSPOT_CSV_CONTACT: "hubspot_csv_contact",
	SELLSY_CONTACT: "sellsy_contact",
	SELLSY_CSV_CONTACT: "sellsy_csv_contact",
	SELLSY_GOOGLE_SHEET_CONTACT: "sellsy_google_sheet_contact",
	GOOGLE_SHEETS_LEAD: "google_sheets_lead",
	ZOHO_LEAD: "zoho_lead",
	ZOHO_CONTACT: "zoho_contact",
	ZOHO_GOOGLE_SHEET_LEAD: "zoho_google_sheet_lead",
	ZOHO_CSV_LEAD: "zoho_csv_lead",
	EXCEL_LEAD: "excel_lead",
	BULLHORN_LEAD: "bullhorn_lead",
	BULLHORN_CONTACT: "bullhorn_contact",
	BULLHORN_CANDIDATE: "bullhorn_candidate",
	BULLHORN_GOOGLE_SHEET_LEAD: "bullhorn_google_sheet_lead",
	BULLHORN_CSV_LEAD: "bullhorn_csv_lead",
	DYNAMICS_LEAD: "dynamics_lead",
	DYNAMICS_CONTACT: "dynamics_contact",
};
