import {
	Tour as TOUR_TRANSLATION,
	Common as COMMON_TRANSLATION,
} from "@cadence-frontend/languages";

export const PRODUCT_TOUR_STATUS = {
	NOT_STARTED: "not_started",
	AFTER_ONBOARDING_PENDING: "after_onboarding_pending",
};

export const PRODUCT_TOUR_STEP_TYPE = {
	INFO: "info",
	CLICK: "click",
	WELCOME_MODAL: "welcome_modal",
	SUCCESS_MODAL: "SUCCESS_MODAL",
};

export const PRODUCT_TOUR_ARROW_POSITION = {
	TOP_LEFT: "top_left",
	TOP_CENTER: "top_center",
	TOP_RIGHT: "top_right",
	BOTTOM_LEFT: "bottom_left",
	BOTTOM_CENTER: "bottom_center",
	BOTTOM_RIGHT: "bottom_right",
	LEFT_TOP: "left_top",
	LEFT_CENTER: "left_center",
	LEFT_BOTTOM: "left_bottom",
	RIGHT_TOP: "right_top",
	RIGHT_CENTER: "right_center",
	RIGHT_BOTTOM: "right_bottom",
};

export const INITIAL_TOUR_STEPS_ENUM = {
	WELCOME_MODAL: "welcome_modal",
	YOUR_CADENCES: "your_cadences",
	YOUR_FIRST_CADENCE: "your_first_cadence",
	CLICK_HERE_TO_CHECK_OUT_YOUR_FIRST_CADENCE:
		"click_here_to_check_out_your_first_cadence",
	CADENCE_STEPS: "cadence_steps",
	YOUR_STEP_INSTRUCTIONS: "your_step_instructions",
	CLICK_PEOPLE: "click_people",
	PEOPLE_TAB: "people_tab",
	OPEN_IMPORT_LEADS_MODAL: "open_import_leads_modal",
	IMPORT_DUMMY_LEADS: "import_dummy_leads",
	LEADS_ADDED: "leads_added",
	LAUNCH_CADENCE: "launch_cadence",
	CADENCE_LAUNCHED_MODAL: "cadence_launched_modal",
	CLICK_TASKS: "click_tasks",
	YOUR_TASKS: "your_tasks",
	TASKS_CREATED: "tasks_created",
	CLICK_FIRST_TASK: "click_first_task",
	CLICK_EMAIL_TASK_CTA: "click_email_task_cta",
	CLICK_SEND_EMAIL: "click_send_email",
	FIRST_TASK_COMPLETED: "first_task_completed",
	CLICK_SECOND_TASK: "click_second_task",
	CLICK_CALL_TASK_CTA: "click_call_task_cta",
	CLICK_HANGUP_CALL: "click_hangup_call",
	CLICK_THIRD_TASK: "click_third_task",
	CLICK_SMS_TASK_CTA: "click_sms_task_cta",
	CLICK_SEND_SMS: "click_send_sms",
	CLICK_FOURTH_TASK: "click_fourth_task",
	CLICK_LINKEDIN_TASK_CTA: "click_linkedin_task_cta",
	CLICK_SEND_LINKEDIN_CONNECTION: "click_send_linkedin_connection",
	DEMO_COMPLETED_MODAL: "demo_completed_modal",
};

export const INITIAL_TOUR_STEPS_ORDER = [
	INITIAL_TOUR_STEPS_ENUM.WELCOME_MODAL,
	INITIAL_TOUR_STEPS_ENUM.YOUR_CADENCES,
	INITIAL_TOUR_STEPS_ENUM.YOUR_FIRST_CADENCE,
	INITIAL_TOUR_STEPS_ENUM.CLICK_HERE_TO_CHECK_OUT_YOUR_FIRST_CADENCE,
	INITIAL_TOUR_STEPS_ENUM.CADENCE_STEPS,
	INITIAL_TOUR_STEPS_ENUM.YOUR_STEP_INSTRUCTIONS,
	INITIAL_TOUR_STEPS_ENUM.CLICK_PEOPLE,
	INITIAL_TOUR_STEPS_ENUM.PEOPLE_TAB,
	INITIAL_TOUR_STEPS_ENUM.OPEN_IMPORT_LEADS_MODAL,
	INITIAL_TOUR_STEPS_ENUM.IMPORT_DUMMY_LEADS,
	INITIAL_TOUR_STEPS_ENUM.LEADS_ADDED,
	INITIAL_TOUR_STEPS_ENUM.LAUNCH_CADENCE,
	INITIAL_TOUR_STEPS_ENUM.CADENCE_LAUNCHED_MODAL,
	INITIAL_TOUR_STEPS_ENUM.CLICK_TASKS,
	INITIAL_TOUR_STEPS_ENUM.YOUR_TASKS,
	INITIAL_TOUR_STEPS_ENUM.TASKS_CREATED,
	INITIAL_TOUR_STEPS_ENUM.CLICK_FIRST_TASK,
	INITIAL_TOUR_STEPS_ENUM.CLICK_EMAIL_TASK_CTA,
	INITIAL_TOUR_STEPS_ENUM.CLICK_SEND_EMAIL,
	INITIAL_TOUR_STEPS_ENUM.FIRST_TASK_COMPLETED,
	INITIAL_TOUR_STEPS_ENUM.CLICK_SECOND_TASK,
	INITIAL_TOUR_STEPS_ENUM.CLICK_CALL_TASK_CTA,
	INITIAL_TOUR_STEPS_ENUM.CLICK_HANGUP_CALL,
	INITIAL_TOUR_STEPS_ENUM.CLICK_THIRD_TASK,
	INITIAL_TOUR_STEPS_ENUM.CLICK_SMS_TASK_CTA,
	INITIAL_TOUR_STEPS_ENUM.CLICK_SEND_SMS,
	INITIAL_TOUR_STEPS_ENUM.CLICK_FOURTH_TASK,
	INITIAL_TOUR_STEPS_ENUM.CLICK_LINKEDIN_TASK_CTA,
	INITIAL_TOUR_STEPS_ENUM.CLICK_SEND_LINKEDIN_CONNECTION,
	INITIAL_TOUR_STEPS_ENUM.DEMO_COMPLETED_MODAL,
];

export const INITIAL_TOUR_STEPS_MAP = {
	[INITIAL_TOUR_STEPS_ENUM.WELCOME_MODAL]: {
		type: PRODUCT_TOUR_STEP_TYPE.WELCOME_MODAL,
	},
	[INITIAL_TOUR_STEPS_ENUM.YOUR_CADENCES]: {
		type: "info",
		title: TOUR_TRANSLATION.YOUR_CADENCES,
		desc: TOUR_TRANSLATION.YOUR_CADENCES_DESC,
		highlightStyle: {
			width: "90px",
			height: "90px",
			top: "50%",
			left: "5px",
			transform: "translateY(-146px)",
			borderRadius: "50%",
		},
		infoStyle: {
			top: "-58px",
			left: "126px",
			width: "440px",
		},
		arrowPosition: PRODUCT_TOUR_ARROW_POSITION.LEFT_CENTER,
		stepCount: {
			current: 1,
			total: 2,
		},
	},
	[INITIAL_TOUR_STEPS_ENUM.YOUR_FIRST_CADENCE]: {
		type: "info",
		title: TOUR_TRANSLATION.YOUR_FIRST_CADENCE,
		desc: TOUR_TRANSLATION.YOUR_FIRST_CADENCE_DESC,
		highlightStyle: {
			width: "90%",
			height: "83px",
			top: "120px",
			left: "122px",
			right: "20px",
			borderRadius: "20px",
		},
		infoStyle: {
			top: "100px",
			left: "50%",
			width: "440px",
			transform: "translateX(-50%)",
		},
		arrowPosition: PRODUCT_TOUR_ARROW_POSITION.TOP_CENTER,
		stepCount: {
			current: 2,
			total: 2,
		},
	},
	[INITIAL_TOUR_STEPS_ENUM.CLICK_HERE_TO_CHECK_OUT_YOUR_FIRST_CADENCE]: {
		isNextStepManual: true,
		type: "click",
		title: TOUR_TRANSLATION.CLICK_TO_CHECKOUT_CADENCE,
		highlightStyle: {
			width: "90%",
			height: "83px",
			top: "99px",
			left: "235px",
			right: "20px",
			borderRadius: "20px",
		},
		clickStyle: {
			top: "35px",
			left: "210px",
			width: "56px",
			height: "56px",
		},
		tooltipStyle: {
			top: "98px",
			left: "238px",
			transform: "translateX(-50%)",
		},
		arrowPosition: PRODUCT_TOUR_ARROW_POSITION.TOP_CENTER,
		onClickButtonId: "#first-cadence",
	},
	[INITIAL_TOUR_STEPS_ENUM.CADENCE_STEPS]: {
		type: "info",
		title: TOUR_TRANSLATION.CADENCE_STEPS,
		desc: TOUR_TRANSLATION.CADENCE_STEPS_DESC,
		highlightStyle: {
			width: "62%",
			height: "540px",
			top: "184px",
			left: "120px",
			borderRadius: "20px",
		},
		infoStyle: {
			top: "3px",
			right: "-49%",
			width: "47%",
		},
		stepCount: {
			current: 1,
			total: 2,
		},
		arrowPosition: PRODUCT_TOUR_ARROW_POSITION.LEFT_TOP,
	},
	[INITIAL_TOUR_STEPS_ENUM.YOUR_STEP_INSTRUCTIONS]: {
		type: "info",
		title: TOUR_TRANSLATION.YOUR_STEP_INSTRUCTIONS,
		desc: TOUR_TRANSLATION.YOUR_STEP_INSTRUCTIONS_DESC,
		highlightStyle: {
			width: "28%",
			height: "calc(100vh - 200px)",
			top: "184px",
			right: "20px",
			borderRadius: "20px",
		},
		infoStyle: {
			top: "30%",
			left: "-460px",
			width: "440px",
		},
		arrowPosition: PRODUCT_TOUR_ARROW_POSITION.RIGHT_CENTER,
		stepCount: {
			current: 2,
			total: 2,
		},
	},
	[INITIAL_TOUR_STEPS_ENUM.CLICK_PEOPLE]: {
		isNextStepManual: true,
		type: "click",
		title: TOUR_TRANSLATION.LETS_EXPLORE_HERE,
		highlightStyle: {
			width: "95px",
			height: "54px",
			top: "112px",
			left: "212px",
		},
		clickStyle: {
			top: "19px",
			left: "20px",
			width: "56px",
			height: "56px",
		},
		arrowPosition: PRODUCT_TOUR_ARROW_POSITION.TOP_LEFT,
		tooltipStyle: {
			top: "83px",
			left: "24px",
		},
		onClickButtonId: "#list-tab-btn",
	},
	[INITIAL_TOUR_STEPS_ENUM.PEOPLE_TAB]: {
		type: "info",
		title: TOUR_TRANSLATION.PEOPLE_TAB,
		desc: TOUR_TRANSLATION.PEOPLE_TAB_DESC,
		highlightStyle: {
			width: "92%",
			height: "calc(100vh - 120px)",
			top: "110px",
			left: "100px",
			borderRadius: "20px",
		},
		highlightClass: "peopleTabHighlight",
		infoStyle: {
			top: "-75px",
			left: "233px",
			width: "440px",
		},
		arrowPosition: PRODUCT_TOUR_ARROW_POSITION.LEFT_CENTER,
		stepCount: {
			current: 1,
			total: 1,
		},
		customNextButton: TOUR_TRANSLATION.SHOW_ME_HOW,
	},
	[INITIAL_TOUR_STEPS_ENUM.OPEN_IMPORT_LEADS_MODAL]: {
		isErrorModalHandling: true,
		type: "click",
		highlightStyle: {
			top: "210px",
			bottom: "17px",
			left: "110px",
			right: "30px",
		},
		clickStyle: {
			left: "50%",
			bottom: "50%",
			transform: "translate(-40%, 150px)",
			width: "56px",
			height: "56px",
		},
		clickColor: "white",
		tooltipStyle: {
			bottom: "50%",
			left: "50%",
			transform: "translate(-45%, 200px)",
		},
		onClickButtonId: "#tour-import-leads-modal-btn",
	},
	[INITIAL_TOUR_STEPS_ENUM.IMPORT_DUMMY_LEADS]: {
		isNextStepManual: true,
		type: "click",
		title: TOUR_TRANSLATION.COMPLETE_THE_IMPORT_PROCESS,
		highlightStyle: {
			left: "50%",
			bottom: "50%",
			height: "50px",
			transform: "translate(-50%, 194px)",
			width: "438px",
		},
		clickStyle: {
			right: "70px",
			width: "56px",
			height: "56px",
		},
		arrowPosition: PRODUCT_TOUR_ARROW_POSITION.BOTTOM_CENTER,
		clickColor: "white",
		tooltipStyle: {
			top: "-55px",
			right: "98px",
			transform: "translateX(50%)",
		},
		onClickButtonId: "#tour-import-leads-btn",
		delay: 5000,
	},
	[INITIAL_TOUR_STEPS_ENUM.LEADS_ADDED]: {
		type: "info",
		title: TOUR_TRANSLATION.LEADS_ADDED_SUCCESSFULLY,
		desc: TOUR_TRANSLATION.SAMPLE_LEADS_ADDED_TO_CADENCE,
		highlightStyle: {
			width: "92%",
			height: "calc(100vh - 120px)",
			top: "110px",
			left: "100px",
			borderRadius: "20px",
		},
		highlightClass: "peopleTabHighlight",
		infoStyle: {
			top: "-85px",
			left: "233px",
			width: "440px",
		},
		arrowPosition: PRODUCT_TOUR_ARROW_POSITION.LEFT_CENTER,
		stepCount: {
			current: 1,
			total: 1,
		},
		customNextButton: TOUR_TRANSLATION.LAUNCH_CADENCE,
	},
	[INITIAL_TOUR_STEPS_ENUM.LAUNCH_CADENCE]: {
		isNextStepManual: true,
		type: "click",
		title: TOUR_TRANSLATION.LAUNCH_FIRST_CADENCE,
		highlightStyle: {
			width: "175px",
			height: "50px",
			top: "35px",
			right: "100px",
		},
		clickStyle: {
			top: "-3px",
			left: "-20px",
			width: "56px",
			height: "56px",
		},
		arrowPosition: PRODUCT_TOUR_ARROW_POSITION.RIGHT_CENTER,
		tooltipStyle: {
			top: "2px",
			left: "-270px",
		},
		onClickButtonId: "#launch-cadence-btn",
	},
	[INITIAL_TOUR_STEPS_ENUM.CADENCE_LAUNCHED_MODAL]: {
		type: PRODUCT_TOUR_STEP_TYPE.SUCCESS_MODAL,
		title: TOUR_TRANSLATION.CADENCE_LAUNCHED,
		desc: TOUR_TRANSLATION.CADENCE_LAUNCHED_DESC,
	},
	[INITIAL_TOUR_STEPS_ENUM.CLICK_TASKS]: {
		isErrorModalHandling: true,
		type: "click",
		title: TOUR_TRANSLATION.TASKS_READY,
		highlightStyle: {
			width: "60px",
			height: "60px",
			top: "50%",
			left: "20px",
			transform: "translateY(-197px)",
			borderRadius: "50%",
		},
		clickStyle: {
			top: "5px",
			left: "20px",
			width: "56px",
			height: "56px",
		},
		arrowPosition: PRODUCT_TOUR_ARROW_POSITION.LEFT_CENTER,
		tooltipStyle: {
			top: "9px",
			left: "85px",
		},
		onClickButtonId: "#tasks-nav-btn",
	},
	[INITIAL_TOUR_STEPS_ENUM.YOUR_TASKS]: {
		isNextStepManual: true,
		type: "info",
		title: TOUR_TRANSLATION.YOUR_TASKS,
		desc: TOUR_TRANSLATION.YOUR_TASKS_DESC,
		highlightStyle: {
			width: "90px",
			height: "90px",
			top: "50%",
			left: "5px",
			transform: "translateY(-210px)",
			borderRadius: "50%",
		},
		infoStyle: {
			top: "48px",
			left: "126px",
			width: "440px",
			transform: "translateY(-50%)",
		},
		arrowPosition: PRODUCT_TOUR_ARROW_POSITION.LEFT_CENTER,
		stepCount: {
			current: 1,
			total: 2,
		},
	},
	[INITIAL_TOUR_STEPS_ENUM.TASKS_CREATED]: {
		type: "info",
		title: TOUR_TRANSLATION.TASKS_CREATED,
		desc: TOUR_TRANSLATION.TASKS_CREATED_DESC,
		highlightStyle: {
			width: "720px",
			height: "calc(100vh - 120px)",
			top: "101px",
			left: "120px",
			borderRadius: "20px",
		},
		infoStyle: {
			top: "70px",
			right: "-63%",
			width: "440px",
		},
		arrowPosition: PRODUCT_TOUR_ARROW_POSITION.LEFT_CENTER,
		stepCount: {
			current: 2,
			total: 2,
		},
		customNextButton: TOUR_TRANSLATION.START,
	},
	[INITIAL_TOUR_STEPS_ENUM.CLICK_FIRST_TASK]: {
		isNextStepManual: true,
		type: "click",
		title: TOUR_TRANSLATION.CLICK_FIRST_TASK,
		highlightStyle: {
			width: "90%",
			height: "83px",
			top: "99px",
			left: "105px",
			right: "20px",
			borderRadius: "20px",
		},
		clickStyle: {
			top: "15px",
			left: "375px",
			width: "56px",
			height: "56px",
		},
		tooltipStyle: {
			top: "-38px",
			left: "379px",
		},
		arrowPosition: PRODUCT_TOUR_ARROW_POSITION.BOTTOM_LEFT,
		taskProgress: {
			current: 1,
			total: 4,
		},
		onClickButtonId: "#first-task",
	},
	[INITIAL_TOUR_STEPS_ENUM.CLICK_EMAIL_TASK_CTA]: {
		isNextStepManual: true,
		type: "click",
		title: TOUR_TRANSLATION.LETS_SEND_EMAIL,
		highlightStyle: {
			top: "380px",
			right: "14%",
			width: "19%",
			height: "50px",
		},
		clickStyle: {
			top: "-3px",
			right: "6px",
			width: "56px",
			height: "56px",
		},
		clickColor: "white",
		arrowPosition: PRODUCT_TOUR_ARROW_POSITION.TOP_CENTER,
		tooltipStyle: {
			top: "60px",
			right: "33px",
			transform: "translateX(50%)",
		},
		onClickButtonId: "#mail-task-cta",
	},
	[INITIAL_TOUR_STEPS_ENUM.CLICK_SEND_EMAIL]: {
		isNextStepManual: true,
		type: "click",
		title: TOUR_TRANSLATION.SEND_EMAIL,
		highlightStyle: {
			left: "50%",
			bottom: "76px",
			height: "50px",
			transform: "translateX(-50%)",
			width: "100%",
			maxWidth: "800px",
			borderRadius: "20px",
		},
		clickStyle: {
			right: "143px",
			width: "56px",
			height: "56px",
		},
		arrowPosition: PRODUCT_TOUR_ARROW_POSITION.BOTTOM_CENTER,
		clickColor: "white",
		tooltipStyle: {
			top: "-55px",
			right: "170px",
			transform: "translateX(50%)",
		},
		onClickButtonId: "#send-mail-btn",
	},
	[INITIAL_TOUR_STEPS_ENUM.FIRST_TASK_COMPLETED]: {
		type: PRODUCT_TOUR_STEP_TYPE.SUCCESS_MODAL,
		title: TOUR_TRANSLATION.FIRST_TASK_COMPLETED,
		desc: TOUR_TRANSLATION.FIRST_TASK_COMPLETED_DESC,
	},
	[INITIAL_TOUR_STEPS_ENUM.CLICK_SECOND_TASK]: {
		isNextStepManual: true,
		type: "click",
		title: TOUR_TRANSLATION.CLICK_SECOND_TASK,
		highlightStyle: {
			width: "45%",
			height: "83px",
			top: "99px",
			left: "105px",
			right: "20px",
			borderRadius: "20px",
		},
		clickStyle: {
			top: "15px",
			left: "375px",
			width: "56px",
			height: "56px",
		},
		arrowPosition: PRODUCT_TOUR_ARROW_POSITION.BOTTOM_LEFT,
		tooltipStyle: {
			top: "-38px",
			left: "379px",
		},
		taskProgress: {
			current: 2,
			total: 4,
		},
		onClickButtonId: "#first-task",
	},
	[INITIAL_TOUR_STEPS_ENUM.CLICK_CALL_TASK_CTA]: {
		isErrorModalHandling: true,
		type: "click",
		title: TOUR_TRANSLATION.CALL_LEAD,
		highlightStyle: {
			top: "393px",
			right: "14%",
			width: "19%",
			height: "50px",
		},
		clickStyle: {
			top: "-3px",
			right: "10px",
			width: "56px",
			height: "56px",
		},
		clickColor: "white",
		arrowPosition: PRODUCT_TOUR_ARROW_POSITION.TOP_CENTER,
		tooltipStyle: {
			top: "60px",
			right: "37px",
			transform: "translateX(50%)",
		},
		onClickButtonId: "#call-task-cta",
	},
	[INITIAL_TOUR_STEPS_ENUM.CLICK_HANGUP_CALL]: {
		isNextStepManual: true,
		type: "click",
		highlightStyle: {
			bottom: "62px",
			right: "50%",
			width: "65px",
			height: "65px",
			transform: "translateX(-110px)",
			borderRadius: "50%",
		},
		onClickButtonId: "#hangup-call-btn",
	},
	[INITIAL_TOUR_STEPS_ENUM.CLICK_THIRD_TASK]: {
		isNextStepManual: true,
		type: "click",
		title: TOUR_TRANSLATION.CLICK_THIRD_TASK,
		highlightStyle: {
			width: "45%",
			height: "83px",
			top: "99px",
			left: "105px",
			right: "20px",
			borderRadius: "20px",
		},
		clickStyle: {
			top: "15px",
			left: "375px",
			width: "56px",
			height: "56px",
		},
		arrowPosition: PRODUCT_TOUR_ARROW_POSITION.BOTTOM_LEFT,
		tooltipStyle: {
			top: "-38px",
			left: "379px",
		},
		taskProgress: {
			current: 3,
			total: 4,
		},
		onClickButtonId: "#first-task",
	},
	[INITIAL_TOUR_STEPS_ENUM.CLICK_SMS_TASK_CTA]: {
		isNextStepManual: true,
		type: "click",
		title: TOUR_TRANSLATION.INITIATE_SMS_TASK,
		highlightStyle: {
			top: "380px",
			right: "14%",
			width: "19%",
			height: "50px",
		},
		clickStyle: {
			top: "-3px",
			right: "10px",
			width: "56px",
			height: "56px",
		},
		clickColor: "white",
		arrowPosition: PRODUCT_TOUR_ARROW_POSITION.TOP_CENTER,
		tooltipStyle: {
			top: "60px",
			right: "37px",
			transform: "translateX(50%)",
		},
		onClickButtonId: "#default-task-cta",
	},
	[INITIAL_TOUR_STEPS_ENUM.CLICK_SEND_SMS]: {
		isNextStepManual: true,
		type: "click",
		title: TOUR_TRANSLATION.SEND_SMS,
		highlightStyle: {
			left: "50%",
			bottom: "84px",
			height: "50px",
			transform: "translateX(-50%)",
			width: "100%",
			maxWidth: "800px",
			borderRadius: "20px",
		},
		clickStyle: {
			right: "141px",
			width: "56px",
			height: "56px",
		},
		clickColor: "white",
		arrowPosition: PRODUCT_TOUR_ARROW_POSITION.BOTTOM_CENTER,
		tooltipStyle: {
			top: "-55px",
			right: "168px",
			transform: "translateX(50%)",
		},
		onClickButtonId: "#send-message-btn",
		delay: 1500,
	},
	[INITIAL_TOUR_STEPS_ENUM.CLICK_FOURTH_TASK]: {
		isNextStepManual: true,
		type: "click",
		title: TOUR_TRANSLATION.CLICK_FOURTH_TASK,
		highlightStyle: {
			width: "45%",
			height: "83px",
			top: "99px",
			left: "105px",
			right: "20px",
			borderRadius: "20px",
		},
		clickStyle: {
			top: "15px",
			left: "375px",
			width: "56px",
			height: "56px",
		},
		arrowPosition: PRODUCT_TOUR_ARROW_POSITION.BOTTOM_LEFT,
		tooltipStyle: {
			top: "-38px",
			left: "382px",
		},
		taskProgress: {
			current: 4,
			total: 4,
		},
		onClickButtonId: "#first-task",
		delay: 1000,
	},
	[INITIAL_TOUR_STEPS_ENUM.CLICK_LINKEDIN_TASK_CTA]: {
		isErrorModalHandling: true,
		type: "click",
		title: TOUR_TRANSLATION.INITIATE_LINKEDIN_TASK,
		highlightStyle: {
			top: "380px",
			right: "14%",
			width: "19%",
			height: "50px",
		},
		clickStyle: {
			top: "-3px",
			right: "10px",
			width: "56px",
			height: "56px",
		},
		clickColor: "white",
		arrowPosition: PRODUCT_TOUR_ARROW_POSITION.TOP_CENTER,
		tooltipStyle: {
			top: "60px",
			right: "37px",
			transform: "translateX(50%)",
		},
		onClickButtonId: "#default-task-cta",
	},
	[INITIAL_TOUR_STEPS_ENUM.CLICK_SEND_LINKEDIN_CONNECTION]: {
		isNextStepManual: true,
		type: "click",
		title: TOUR_TRANSLATION.SEND_CONNECTION,
		highlightStyle: {
			left: "50%",
			bottom: "102px",
			height: "50px",
			transform: "translateX(-50%)",
			width: "100%",
			maxWidth: "800px",
			borderRadius: "20px",
		},
		clickStyle: {
			right: "174px",
			width: "56px",
			height: "56px",
		},
		clickColor: "white",
		arrowPosition: PRODUCT_TOUR_ARROW_POSITION.BOTTOM_CENTER,
		tooltipStyle: {
			top: "-55px",
			right: "201px",
			transform: "translateX(50%)",
		},
		onClickButtonId: "#complete-linkedin-task-btn",
		delay: 500,
	},
	[INITIAL_TOUR_STEPS_ENUM.DEMO_COMPLETED_MODAL]: {
		type: PRODUCT_TOUR_STEP_TYPE.SUCCESS_MODAL,
		title: TOUR_TRANSLATION.DEMO_COMPLETED,
		desc: TOUR_TRANSLATION.DEMO_COMPLETED_DESC,
	},
};
