import { ROLES } from "@cadence-frontend/constants";
import { Common as COMMON_TRANSLATION } from "@cadence-frontend/languages";

export const ROLES_MAP = {
	[ROLES.ADMIN]: COMMON_TRANSLATION.ADMIN,
	[ROLES.SUPER_ADMIN]: COMMON_TRANSLATION.SUPER_ADMIN,
	[ROLES.SALESPERSON]: COMMON_TRANSLATION.SALES_AGENT,
	[ROLES.MANAGER]: COMMON_TRANSLATION.MANAGER,
	[ROLES.SALES_MANAGER]: COMMON_TRANSLATION.SALES_MANAGER,
};
