import { INTEGRATION_TYPE } from "@cadence-frontend/constants";

export const INTEGRATION_MAP_KEYS = {
	[INTEGRATION_TYPE.SALESFORCE]: {
		lead: "lead_map",
		contact: "contact_map",
		account: "account_map",
	},
	[INTEGRATION_TYPE.PIPEDRIVE]: {
		person: "lead_map",
		organization: "organization_map",
	},
	[INTEGRATION_TYPE.HUBSPOT]: {
		contact: "contact_map",
		company: "company_map",
	},
	[INTEGRATION_TYPE.SELLSY]: {
		contact: "contact_map",
		company: "company_map",
	},
	[INTEGRATION_TYPE.DYNAMICS]: {
		lead: "lead_map",
		contact: "contact_map",
		account: "account_map",
	},
	[INTEGRATION_TYPE.ZOHO]: {
		lead: "lead_map",
		contact: "contact_map",
		account: "account_map",
	},
	[INTEGRATION_TYPE.BULLHORN]: {
		lead: "lead_map",
		contact: "contact_map",
		account: "account_map",
		candidate: "candidate_map",
	},
};

export const INTEGRATION_FIELDS_AVAILABLE = {
	[INTEGRATION_TYPE.SALESFORCE]: {
		lead: [
			"linkedin_url",
			"url",
			"first_name",
			"last_name",
			"job_position",
			"company",
			"size",
			"emails",
			"phone_numbers",
			"company_phone_number",
			"zip_code",
			"country",
			"integration_status",
			"qualification",
		],
		contact: [
			"linkedin_url",
			"url",
			"first_name",
			"last_name",
			"job_position",
			"company",
			"size",
			"emails",
			"phone_numbers",
			"company_phone_number",
			"zip_code",
			"country",
			"integration_status",
			"qualification",
		],
	},
	[INTEGRATION_TYPE.PIPEDRIVE]: {
		person: [
			"linkedin_url",
			"first_name",
			"last_name",
			"job_position",
			"emails",
			"phone_numbers",
			"integration_status",
			"qualification",
		],
		organization: [
			"url",
			"company",
			"size",
			"company_phone_number",
			"zip_code",
			"country",
		],
	},
	[INTEGRATION_TYPE.HUBSPOT]: {
		contact: [
			"linkedin_url",
			"first_name",
			"last_name",
			"job_position",
			"emails",
			"phone_numbers",
			"integration_status",
			"qualification",
		],
		company: ["url", "company", "size", "company_phone_number", "zip_code", "country"],
	},
	[INTEGRATION_TYPE.SELLSY]: {
		contact: [
			"linkedin_url",
			"first_name",
			"last_name",
			"job_position",
			"emails",
			"phone_numbers",
			"integration_status",
		],
		company: ["url", "company", "size", "company_phone_number", "zip_code", "country"],
	},
	[INTEGRATION_TYPE.DYNAMICS]: {
		lead: [
			"linkedin_url",
			"url",
			"first_name",
			"last_name",
			"job_position",
			"company",
			"size",
			"emails",
			"phone_numbers",
			"company_phone_number",
			"zip_code",
			"country",
			"integration_status",
			"qualification",
		],
		contact: [
			"linkedin_url",
			"url",
			"first_name",
			"last_name",
			"job_position",
			"company",
			"size",
			"emails",
			"phone_numbers",
			"company_phone_number",
			"zip_code",
			"country",
			"integration_status",
			"qualification",
		],
	},
	[INTEGRATION_TYPE.ZOHO]: {
		lead: [
			"linkedin_url",
			"url",
			"first_name",
			"last_name",
			"job_position",
			"company",
			"size",
			"emails",
			"phone_numbers",
			"company_phone_number",
			"zip_code",
			"country",
			"integration_status",
			"qualification",
		],
		contact: [
			"linkedin_url",
			"url",
			"first_name",
			"last_name",
			"job_position",
			"company",
			"size",
			"emails",
			"phone_numbers",
			"company_phone_number",
			"zip_code",
			"country",
			"integration_status",
			"qualification",
		],
	},
	[INTEGRATION_TYPE.BULLHORN]: {
		lead: [
			"linkedin_url",
			"url",
			"first_name",
			"last_name",
			"job_position",
			"company",
			"size",
			"emails",
			"phone_numbers",
			"company_phone_number",
			"zip_code",
			"country",
			"integration_status",
			"qualification",
		],
		candidate: [
			"linkedin_url",
			"url",
			"first_name",
			"last_name",
			"job_position",
			"company",
			"size",
			"emails",
			"phone_numbers",
			"company_phone_number",
			"zip_code",
			"country",
			"integration_status",
			"qualification",
		],
		contact: [
			"linkedin_url",
			"url",
			"first_name",
			"last_name",
			"job_position",
			"company",
			"size",
			"emails",
			"phone_numbers",
			"company_phone_number",
			"zip_code",
			"country",
			"integration_status",
			"qualification",
		],
	},
};
