import { INTEGRATION_TYPE } from "@cadence-frontend/constants";

export const INSTALL_PACKAGE_AVAILABLE = [INTEGRATION_TYPE.SALESFORCE];

export const DATA_CENTER_AVAILABLE = [INTEGRATION_TYPE.ZOHO];

export const API_TOKEN_AVAILABLE = [INTEGRATION_TYPE.SALESFORCE];

export const FIELD_MAPPING_AVAILABLE = [
	INTEGRATION_TYPE.SALESFORCE,
	INTEGRATION_TYPE.HUBSPOT,
	INTEGRATION_TYPE.PIPEDRIVE,
	INTEGRATION_TYPE.ZOHO,
	INTEGRATION_TYPE.SELLSY,
	INTEGRATION_TYPE.DYNAMICS,
	INTEGRATION_TYPE.BULLHORN,
];

export const DATA_CENTER_OPTIONS = {
	"Rest of the world": "rest of the world",
	China: "china",
};
